import { useMemo, useState, type ReactNode } from "react"
import { Banner } from "./ui/Banner"
import { CaptureScreen } from "./ui/CaptureScreen"
import { downloadDataUrl, downloadJson } from "./lib/download"
import { flipFirstByte, sha256Hex } from "./lib/hash"
import { type CalibrationShotId } from "./lib/shots"
import { loadRecords, saveRecord, type TestRecord } from "./lib/store"
import { loadImage } from "./lib/camera"
import { evidencePayload, verifyRecordSeal } from "./lib/seal"

type Page = "login" | "capture" | "result" | "record" | "log"
type Analysis = { confidence?: string; confidenceScore?: number }
const RESULT_COPY = {
  positive: ["Presumptive positive", "The observed colour is consistent with the configured positive reference.", "Seal this field observation and retain the sample for laboratory confirmation."],
  negative: ["Presumptive negative", "The observed colour is consistent with the configured negative reference.", "This remains a presumptive field observation; follow your operational protocol."],
  inconclusive: ["Inconclusive", "The image quality or colour match was not reliable enough for a field call.", "Retake the photo with the colour card visible, evenly lit, and free of glare."],
} as const

function parseAnalysis(value: string): Analysis { try { return JSON.parse(value) as Analysis } catch { return {} } }
function Header({ page, onLog }: { page: Page; onLog: () => void }) { return <header className="topbar"><div className="brand"><span className="brand-mark">◆</span><div>NCB Field Notes<small>digital companion for colour tests</small></div></div><div className="topbar-meta"><span>SIH26231</span>{page !== "login" ? <button className="text-button" onClick={onLog}>Field log</button> : null}</div></header> }
function Workflow({ active }: { active: "capture" | "result" | "record" }) { const steps = ["capture", "result", "record"] as const; return <div className="workflow" aria-label="Test workflow">{steps.map((step, i) => <div className={`workflow-step ${step === active ? "active" : ""}`} key={step}><span>{i + 1}</span>{step === "record" ? "seal" : step}</div>)}</div> }

export default function App() {
  const [page, setPage] = useState<Page>("login")
  const [officerId, setOfficerId] = useState(() => sessionStorage.getItem("sih26231.officer") ?? "")
  const [draftId, setDraftId] = useState(officerId)
  const [current, setCurrent] = useState<TestRecord | null>(null)
  const [debug, setDebug] = useState("")
  const [query, setQuery] = useState("")
  const [flippedHash, setFlippedHash] = useState<string | null>(null)
  const [sealVerified, setSealVerified] = useState<boolean | null>(null)
  const [shotId, setShotId] = useState<CalibrationShotId | "">("")
  const records = useMemo(() => loadRecords(), [page, current])
  const analysis = useMemo(() => parseAnalysis(debug), [debug])
  function enter() { const id = draftId.trim(); if (!id) return; sessionStorage.setItem("sih26231.officer", id); setOfficerId(id); setPage("capture") }
  function afterCapture(record: TestRecord, classifiedJson: string) { saveRecord(record); setCurrent(record); setDebug(classifiedJson); setFlippedHash(null); setSealVerified(null); setPage("result") }
  async function proveHashMoves() { if (!current) return; const img = await loadImage(current.imageDataUrl); const canvas = document.createElement("canvas"); canvas.width = img.naturalWidth; canvas.height = img.naturalHeight; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.drawImage(img, 0, 0); const blob: Blob = await new Promise((resolve, reject) => canvas.toBlob((b) => b ? resolve(b) : reject(new Error("blob")), "image/jpeg", 0.92)); setFlippedHash(await sha256Hex(flipFirstByte(await blob.arrayBuffer()))) }

  return <main className="app"><Header page={page} onLog={() => setPage("log")} />
    {page === "login" && <section className="welcome"><div className="eyebrow">Field documentation · colour-change kit</div><h1>Turn a colour change into a record you can stand behind.</h1><p className="lead">This companion does not test the substance. It helps you photograph the existing kit fairly, record what was observed, and preserve that observation.</p><Banner /><div className="field-note"><span>Before you begin</span><p>Keep the printed reference card and the kit result in the same frame. Avoid direct glare on the vial or strip.</p></div><div className="how-it-works"><div><b>01</b><span>Place card + kit</span></div><div><b>02</b><span>Review observation</span></div><div><b>03</b><span>Seal field note</span></div></div><div className="card login-card"><label htmlFor="oid">Who is documenting this test?</label><input id="oid" value={draftId} onChange={(e) => setDraftId(e.target.value)} placeholder="Enter officer / operator ID" autoComplete="off" /><p className="field-help">This identifier is included in the sealed record. It is not a login or identity check.</p></div><button className="primary" onClick={enter} disabled={!draftId.trim()}>Begin field observation <span>→</span></button><button className="ghost" onClick={() => setPage("log")}>Find an earlier field note</button></section>}
    {page === "capture" && <><Workflow active="capture" /><CaptureScreen officerId={officerId} shotId={shotId} onShotId={setShotId} onCaptured={afterCapture} onLog={() => setPage("log")} /></>}
    {page === "result" && current && <><Workflow active="result" /><section className="result-screen"><div className="eyebrow">What the camera observed</div><div className={`result-panel ${current.result}`}><span className="result-icon">{current.result === "positive" ? "+" : current.result === "negative" ? "−" : "!"}</span><div><h1>{RESULT_COPY[current.result][0]}</h1><p>{RESULT_COPY[current.result][1]}</p></div></div><Banner /><figure className="capture-figure"><img className="evidence-photo" src={current.imageDataUrl} alt="Captured field-test image" /><figcaption>Captured image · card and kit observed in one frame</figcaption></figure><div className="quality-card"><div><span>Image check</span><strong>{current.flags.length ? "Needs another look" : "Card and kit look usable"}</strong></div><div><span>Colour match</span><strong>{analysis.confidence ? `${analysis.confidence} · ${analysis.confidenceScore}/100` : "Recorded"}</strong></div></div>{current.flags.length ? <p className="quality-warning">The app noticed: {current.flags.join(", ").replaceAll("_", " ")}. {RESULT_COPY.inconclusive[2]}</p> : <p className="next-step">Next: {RESULT_COPY[current.result][2]}</p>}<button className="primary" onClick={() => setPage("record")}>Read and seal field note <span>→</span></button><button className="ghost" onClick={() => setPage("capture")}>Take another photo</button><details className="technical-details"><summary>Why this call was made</summary><p>Calibration: {current.method}. The app compares the corrected kit colour against stored reference colours; it does not identify a drug.</p><pre>{debug}</pre></details>{shotId ? <details className="technical-details"><summary>Calibration study export</summary><button className="ghost" onClick={() => { const name = shotId; downloadDataUrl(`${name}.jpg`, current.imageDataUrl); downloadJson(`${name}.json`, { shotId: name, result: current.result, method: current.method, flags: current.flags, debug: analysis }); setShotId("") }}>Download this calibration sample</button></details> : null}</section></>}
    {page === "record" && current && <><Workflow active="record" /><section><div className="eyebrow">Evidence record</div><h1>Field observation sealed</h1><Banner /><div className="seal-status"><span>✓</span><div><strong>Image and record metadata are protected</strong><p>A digital signature detects later changes to this record.</p></div></div><div className="record-grid"><Field label="Officer" value={current.officerId} /><Field label="Captured (UTC)" value={current.capturedAt.replace("T", " ").replace("Z", " UTC")} /><Field label="Location" value={current.lat != null && current.lon != null ? `${current.lat.toFixed(5)}, ${current.lon.toFixed(5)} ±${current.gpsAccuracyM ?? "?"} m` : "Location unavailable"} /><Field label="Field call" value={<span className={`chip ${current.result}`}>{current.result}</span>} /><Field label="Image fingerprint (SHA-256)" value={<span className="mono">{current.sha256Hex}</span>} full /><Field label="Signature" value={current.seal ? `P-256 · device key ${current.seal.keyId}` : "Legacy record — unsigned"} full /></div>{sealVerified != null ? <p className={sealVerified ? "seal-ok" : "seal-bad"}>{sealVerified ? "✓ Signature verified. The sealed data has not changed." : "✕ Verification failed — do not rely on this record."}</p> : null}<button className="primary" onClick={() => void verifyRecordSeal(current, current.seal).then(setSealVerified)}>Verify sealed record</button><button className="ghost" onClick={() => downloadJson(`SIH26231-evidence-${current.id}.json`, evidencePayload(current, current.seal))}>Export evidence package</button><button className="ghost" onClick={() => setPage("log")}>View test log</button><details className="technical-details"><summary>Demonstrate tamper detection</summary><p>For the demo only: simulate changing one byte in the captured image.</p><button className="ghost" onClick={() => void proveHashMoves()}>Simulate image change</button>{flippedHash ? <p className="mono hash-flip">Changed-image hash: {flippedHash}</p> : null}</details></section></>}
    {page === "log" && <LogScreen query={query} onQuery={setQuery} records={records} onOpen={(r) => { setCurrent(r); setDebug(""); setSealVerified(null); setPage("record") }} onNew={() => setPage(officerId ? "capture" : "login")} />}
  </main>
}

function Field({ label, value, full = false }: { label: string; value: ReactNode; full?: boolean }) { return <div className={full ? "record-field full" : "record-field"}><span>{label}</span><strong>{value}</strong></div> }
function LogScreen(props: { query: string; onQuery: (q: string) => void; records: TestRecord[]; onOpen: (r: TestRecord) => void; onNew: () => void }) { const q = props.query.trim().toLowerCase(); const rows = props.records.filter((r) => !q || r.officerId.toLowerCase().includes(q) || r.result.includes(q) || r.sha256Hex.includes(q)); return <section><div className="eyebrow">Secure local log</div><h1>Test records</h1><p className="lead small">Search by officer ID, field call, or image fingerprint.</p><input value={props.query} onChange={(e) => props.onQuery(e.target.value)} placeholder="Search records" aria-label="Search test records" /><div className="list">{rows.length === 0 ? <div className="empty-state">No matching records.</div> : rows.map((r) => <button key={r.id} className="item" onClick={() => props.onOpen(r)}><strong className={`chip ${r.result}`}>{r.result}</strong><div><b>{r.officerId}</b><span>{r.capturedAt.replace("T", " ").slice(0, 19)} UTC</span></div><span className="item-arrow">→</span></button>)}</div><button className="primary" onClick={props.onNew}>New field test <span>→</span></button></section> }
